#! /bin/sh

# sanity check
if [ -z "$OECORE_TARGET_SYSROOT" ]; then
	echo "E: No SDK environment setup" >&2
	exit 1
fi

# This will build protobuf's protoc compiler for the host platform using host tools
# and use it for the C++ codegen
make -f openfmb.mk "$@" || exit 1

# build protobuf for the target
make -f protobuf-target.mk "$@" || exit 1

# build app
make "$@" || exit 1
