ROOT_DIR ?= $(dir $(realpath $(firstword $(MAKEFILE_LIST))))

PROTOBUF_SOURCE_DIR ?= $(ROOT_DIR)/protobuf-build
PROTOBUF_CONFIGURE = $(PROTOBUF_SOURCE_DIR)/configure

PROTOBUF_VERSION=v3.16.0

PROTOC_BUILD_DIR ?= $(PROTOBUF_SOURCE_DIR)/host-build
PROTOC_MAKEFILE = $(PROTOBUF_BUILD_DIR)/Makefile
PROTOC_INSTALL_DIR ?= $(PROTOBUF_SOURCE_DIR)/host-install

TARGET_PROTOBUF_BUILD_DIR ?= $(PROTOBUF_SOURCE_DIR)/target-build
TARGET_PROTOBUF_PREFIX ?= $(PROTOBUF_SOURCE_DIR)/target-install
TARGET_PROTOBUF_INSTALL_PREFIX ?= $(TARGET_PROTOBUF_PREFIX)
TARGET_PROTOBUF_MAKEFILE ?= $(TARGET_PROTOBUF_BUILD_DIR)/Makefile
TARGET_PROTOBUF_LIB ?= $(TARGET_PROTOBUF_INSTALL_PREFIX)/lib/libprotobuf.a
TARGET_PROTOBUF_INCLUDE = $(TARGET_PROTOBUF_INSTALL_PREFIX)/include
TARGET_PROTOBUF_PKG_CONFIG_PATH = $(TARGET_PROTOBUF_INSTALL_PREFIX)/lib/pkgconfig

$(info TARGET_PROTOBUF_PKG_CONFIG_PATH=$(TARGET_PROTOBUF_PKG_CONFIG_PATH))

#TARGET_PROTOBUF_LIBS += $(TARGET_PROTOBUF_LIB)
TARGET_PROTOBUF_CXXFLAGS += -I$(TARGET_PROTOBUF_INCLUDE)

$(PROTOBUF_SOURCE_DIR)/autogen.sh:
	git clone --branch=$(PROTOBUF_VERSION) https://github.com/protocolbuffers/protobuf.git protobuf-build

$(PROTOBUF_CONFIGURE): $(PROTOBUF_SOURCE_DIR)/autogen.sh
	cd $(PROTOBUF_SOURCE_DIR) ; \
	env ./autogen.sh
